<?php
if ($block->getConfigValue(''))
?>
<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */
echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */
            echo __('Additional Information') ?></span></legend>
    <br></p>

    <p>
    <div class="field my_attribute required">
        <label for="linkedin_profile" class="label"><span><?php /* @escapeNotVerified */
                echo __('LinkedIn Profile') ?></span></label>
        <div class="control">
            <input type="text" name="linkedin_profile" id="linkedin_profile" title="<?php /* @escapeNotVerified */
            echo __('LinkedIn Profile') ?>" class="input-text" data-validate="{required:true}" autocomplete="off">
        </div>
    </div>
    </div>
</fieldset>