<?php
if ($block->getConfigValue('redboxdigital_linkedin/general/is_visible')) :
    $isRequired = $block->getConfigValue('redboxdigital_linkedin/general/is_visible') == 1 ? true : false;
    ?>
    <fieldset class="fieldset create account" data-hasrequired="<?php if ($isRequired) {
        /* @escapeNotVerified */
        echo __('* Required Fields');
    } ?>">
        <legend class="legend">
            <span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span>
        </legend>
        <div class="field my_attribute">
            <label for="linkedin_profile" class="label">
                <span><?php /* @escapeNotVerified */ echo __('LinkedIn Profile') ?></span>
            </label>
            <div class="control">
                <input type="text" name="linkedin_profile" id="linkedin_profile" title="<?php /* @escapeNotVerified */
                echo __('LinkedIn Profile') ?>" class="input-text"
                    <?php if ($isRequired) { ?> data-validate="{maxlength:250,required:true" <?php } else { ?> data-validate="{maxlength:250}"  <?php } ?>
                       autocomplete="off" value="<?= $this->getLinkedinProfile() ?>" />
            </div>
        </div>
    </fieldset>
<?php endif; ?>